feat: add regiao area desafio armadilha provacao ddls
SBD1/2024.1-PercyJackson pull request #7
Opened 2024-08-07 19:55 UTC by owhenrique

2024-08-08 11:31 UTC, Neitan2001 requested changes

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    nivel       INTEGER     NOT NULL DEFAULT 1,
```suggestion
    nivel       INTEGER     NOT NULL,
```

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    nivel       INTEGER     NOT NULL DEFAULT 1,
O nível da região não precisa ter valor padrão já que iremos definir na mão na hora de criar e o nível não mudará

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    desafio         INTEGER     NOT NULL,
```suggestion
    desafio         INTEGER ,
```

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    desafio         INTEGER     NOT NULL,
O desafio pode ser nulo já que nem todas as áres terão desafio, colocar um desafio em cada área daria muito trabalho

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    areaTeletransporte  VARCHAR(15) DEFAULT NULL,
```suggestion
    areaTeletransporte  VARCHAR(15) NOT NULL,
```

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    areaTeletransporte  VARCHAR(15) DEFAULT NULL,
Toda armadilha irá levar o jogador para algum lugar, então esse atributo não pode ser nulo

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    tipo     CHAR   NOT NULL CHECK(tipo = 'A' OR tipo = 'P')
```suggestion
    tipo     CHAR   NOT NULL CHECK(tipo = 'A' OR tipo = 'P'),
```

2024-08-08 11:31 UTC, Neitan2001 commented on src/init.sql
> +    tipo     CHAR   NOT NULL CHECK(tipo = 'A' OR tipo = 'P')
Faltou uma vírgula aqui, está dando erro de sintaxe sem ela

2024-08-08 15:35 UTC, owhenrique commented on src/init.sql
> +    areaTeletransporte  VARCHAR(15) DEFAULT NULL,
Eu estava imaginando que nem toda armadilha teletransportaria pra algum lugar, algumas só dariam dano ao jogar ou coisa do tipo.

2024-08-18 13:43 UTC, clara-ribeiro commented on src/init.sql
> +);
Na tabela de área não deveria ter as coordenadas tambem? Norte, Sul, Leste e Oeste? Acho que com elas que vamos conseguir fazer os personagens movimentarem-se.

2024-08-19 15:59 UTC, closed without merging